nameOverride: "__PATTERN_NAME__"

env:
  MODEL_ID: "__FM_MODEL_ID__"
  MAAS_BASE_URL: ""
  EMBEDDING_MODEL_ID: "__EMBEDDING_MODEL_ID__"
  EMBEDDING_DIMENSION: "__EMBEDDING_DIMENSION__"
  PROVIDER_TYPE: "__PROVIDER_TYPE__"
  RETRIEVAL_METHOD: "__RETRIEVAL_METHOD__"
  NUMBER_OF_CHUNKS: "__NUMBER_OF_CHUNKS__"
  SEARCH_MODE: "__SEARCH_MODE__"
  RANKER_STRATEGY: "__RANKER_STRATEGY__"
  RANKER_ALPHA: "__RANKER_ALPHA__"

secrets:
  maas_secret_name: "__MAAS_SECRET_NAME__"
  vector_db_secret_name: "__VECTOR_DB_SECRET_NAME__"
